config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rosters
  # get 'home/index'
  get 'home/about'
  # root 'home#index' # home page
  root 'rosters#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/roster.rb
class Roster < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rosters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private
	def after_sign_up_path_for(resource_or_scope)
		home_index_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is Mary Gwozdz..." #instance variable as opposed to a local variable

    @answer = 2 + 2

  end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :set_roster, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: []
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /rosters or /rosters.json
  def index
    if Roster.exists?(:user_id => current_user.id)
      @rosters = Roster.where(user_id: current_user.id).map(&:attributes)
    else
      @rosters = []
    end
  end

  # GET /rosters/1 or /rosters/1.json
  def show
    if @roster == nil
      redirect_to rosters_path
    end
  end

  # GET /rosters/new
  def new
    # @roster = Roster.new
    @roster = current_user.rosters.build
  end

  # GET /rosters/1/edit
  def edit
    if @roster == nil
      redirect_to rosters_path
    end
  end

  # POST /rosters or /rosters.json
  def create
    # @roster = Roster.new(roster_params)
    @roster = current_user.rosters.build(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to roster_url(@roster), notice: "Roster was successfully created." }
        format.json { render :show, status: :created, location: @roster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1 or /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to roster_url(@roster), notice: "Roster was successfully updated." }
        format.json { render :show, status: :ok, location: @roster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1 or /rosters/1.json
  def destroy
    @roster.destroy

    respond_to do |format|
      format.html { redirect_to rosters_url, notice: "Roster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    if Roster.exists?(params[:id])
      @roster = current_user.rosters.find_by(id: params[:id])
      redirect_to rosters_path, notice: "Not Authorized to Edit This Roster" if @roster.nil?
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      if Roster.exists?(params[:id])
        @roster = Roster.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def roster_params
      params.require(:roster).permit(:first_name, :last_name, :email, :phone, :user_id, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Roster App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Student", new_roster_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

<p><%= @about_me %></p>
<p> 2 + 2 = <%= @answer %> </p>

<!-- not best practice -->
<p> <% value = 2 + 3 %> </p>
<p> 2 + 3 = <%= value %> </p>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>Roster App</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end%>

      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/rosters/_form.html.erb
<%= form_with(model: roster) do |form| %>
  <% if roster.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
        <% roster.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id, id: :roster_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/rosters/_roster.html.erb
<div id="<%= dom_id roster %>">
  <p>
    <strong>First name:</strong>
    <%= roster.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= roster.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= roster.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= roster.phone %>
  </p>

</div>

app/views/rosters/edit.html.erb
<h1>Editing Student</h1>
<br/>

<%= render "form", roster: @roster %>

<br>

<div>
  <%= link_to "Show", @roster, class:"btn btn-secondary" %>
  <%= link_to "Delete", @roster, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <%= link_to "Back", rosters_path, class:"btn btn-dark" %>
</div>

app/views/rosters/index.html.erb
<div id="rosters">
  <% if !@rosters.kind_of?(Array) %>
    <% @rosters = [@rosters] %>
  <% end %>
  <% if @rosters.empty? %>
    <div>
      No students in roster.
    </div>
    <br/>
  <% else %>
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @rosters.each do |roster| %>
          <% if roster['user_id'] == current_user.id %>
            <tr>
              <td><%= link_to roster['first_name'] + ' ' + roster['last_name'], roster_path(roster['id']) %></td>
              <td><%= roster['email'] %></td>
              <td><%= roster['phone'] %></td>
              <td><%= link_to "Delete", roster_path(roster['id']), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>
            </tr>
          <% end %>
        <% end %>  
      </tbody>
    </table>
  <% end %>
</div>

<%= link_to "New Student", new_roster_path, class: "btn btn-secondary" %>

app/views/rosters/new.html.erb
<h1>New Student</h1>
<br/>

<%= render "form", roster: @roster %>

<br>

<div>
  <%= link_to "Back", rosters_path, class:"btn btn-dark" %>
</div>

app/views/rosters/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @roster.first_name %> <%= @roster.last_name %></h1>
  <p class="lead"><%= @roster.email %>    | <%= @roster.phone %></p>
  <br/>
  <%= link_to "Edit", edit_roster_path(@roster), class:"btn btn-secondary" %> 
  <%= link_to "Delete", @roster, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <%= link_to "Back", rosters_path, class:"btn btn-dark" %>
</div>